config/routes.rb
Rails.application.routes.draw do
  resources :recipes do
  member do
    get "vote"
  end
end

  resources :categories

  resources :occasions

  resources :diets

  resources :cusines

  resources :eases

  resources :preferences

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'recipes#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/preference.rb
class Preference < ActiveRecord::Base
  belongs_to :user
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_preference, only: [:show, :edit, :update, :destroy]

  # GET /preferences
  # GET /preferences.json
  def index
    @preferences = Preference.all
  end

  # GET /preferences/1
  # GET /preferences/1.json
  def show
  end

  # GET /preferences/new
  def new
    @preference = Preference.new
  end

  # GET /preferences/1/edit
  def edit
  end

  # POST /preferences
  # POST /preferences.json
  def create
    @preference = Preference.new(preference_params)
    @preference.user = current_user

    respond_to do |format|
      if @preference.save
        format.html { redirect_to @preference, notice: 'Preference was successfully created.' }
        format.json { render :show, status: :created, location: @preference }
      else
        format.html { render :new }
        format.json { render json: @preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /preferences/1
  # PATCH/PUT /preferences/1.json
  def update
    respond_to do |format|
      if @preference.update(preference_params)
        format.html { redirect_to @preference, notice: 'Preference was successfully updated.' }
        format.json { render :show, status: :ok, location: @preference }
      else
        format.html { render :edit }
        format.json { render json: @preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preferences/1
  # DELETE /preferences/1.json
  def destroy
    @preference.destroy
    respond_to do |format|
      format.html { redirect_to preferences_url, notice: 'Preference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preference
      @preference = Preference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preference_params
      params.require(:preference).permit(:user_id, :mail, :seasonalmail, :updates, :polls, :searchable, :postfb, :posttw, :postpin, :partnershare, :diet, :allergy, :dislike)
    end
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/views/preferences/_form.html.erb
<%= form_for @preference, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :mail, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :mail, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :seasonalmail, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :seasonalmail, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :updates, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :updates, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :polls, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :polls, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :searchable, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :searchable, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :postfb, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :postfb, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :posttw, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :posttw, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :postpin, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :postpin, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :partnershare, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :partnershare, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :diet, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :diet, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :allergy, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :allergy, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :dislike, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :dislike, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  preferences_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/preferences/edit.html.erb
<%- model_class = Preference -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Preference %></h1>
</div>
<%= render :partial => 'form' %>

app/views/preferences/index.html.erb
<%- model_class = Preference -%>
<div class="page-header">
  <h1><%=t '.title', :default => Preference %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:mail) %></th>
      <th><%= model_class.human_attribute_name(:seasonalmail) %></th>
      <th><%= model_class.human_attribute_name(:updates) %></th>
      <th><%= model_class.human_attribute_name(:polls) %></th>
      <th><%= model_class.human_attribute_name(:searchable) %></th>
      <th><%= model_class.human_attribute_name(:postfb) %></th>
      <th><%= model_class.human_attribute_name(:posttw) %></th>
      <th><%= model_class.human_attribute_name(:postpin) %></th>
      <th><%= model_class.human_attribute_name(:partnershare) %></th>
      <th><%= model_class.human_attribute_name(:diet) %></th>
      <th><%= model_class.human_attribute_name(:allergy) %></th>
      <th><%= model_class.human_attribute_name(:dislike) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @preferences.each do |preference| %>
      <tr>
        <td><%= preference.id %></td>
        <td><%= preference.mail %></td>
        <td><%= preference.seasonalmail %></td>
        <td><%= preference.updates %></td>
        <td><%= preference.polls %></td>
        <td><%= preference.searchable %></td>
        <td><%= preference.postfb %></td>
        <td><%= preference.posttw %></td>
        <td><%= preference.postpin %></td>
        <td><%= preference.partnershare %></td>
        <td><%= preference.diet %></td>
        <td><%= preference.allergy %></td>
        <td><%= preference.dislike %></td>
        <td><%=l preference.created_at, format: :long %></td>
        <td>
          <%= link_to preference_path(preference), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to preference_path(preference), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_preference_path,
            :class => 'btn btn-primary' %>

app/views/preferences/new.html.erb
<%- model_class = Preference -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Preference %></h1>
</div>
<%= render :partial => 'form' %>

app/views/preferences/show.html.erb
<%- model_class = Preference -%>
<div class="page-header">
  <h1><%=t '.title', :default => Preference %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:mail) %></dt>
      <dd><pre class="prettyprint"><%= @preference.mail %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:seasonalmail) %></dt>
      <dd><pre class="prettyprint"><%= @preference.seasonalmail %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:updates) %></dt>
      <dd><pre class="prettyprint"><%= @preference.updates %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:polls) %></dt>
      <dd><pre class="prettyprint"><%= @preference.polls %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:searchable) %></dt>
      <dd><pre class="prettyprint"><%= @preference.searchable %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:postfb) %></dt>
      <dd><pre class="prettyprint"><%= @preference.postfb %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:posttw) %></dt>
      <dd><pre class="prettyprint"><%= @preference.posttw %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:postpin) %></dt>
      <dd><pre class="prettyprint"><%= @preference.postpin %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:partnershare) %></dt>
      <dd><pre class="prettyprint"><%= @preference.partnershare %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:diet) %></dt>
      <dd><pre class="prettyprint"><%= @preference.diet %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:allergy) %></dt>
      <dd><pre class="prettyprint"><%= @preference.allergy %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:dislike) %></dt>
      <dd><pre class="prettyprint"><%= @preference.dislike %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              preferences_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_preference_path(@preference), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              preference_path(@preference),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>