config/routes.rb
Rails.application.routes.draw do
  resources :recipes do
  member do
    get "vote"
  end
end

  resources :categories

  resources :occasions

  resources :diets

  resources :cusines

  resources :eases

  resources :preferences

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'recipes#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/diet.rb
class Diet < ActiveRecord::Base
  has_and_belongs_to_many :recipes
end

app/controllers/diets_controller.rb
class DietsController < ApplicationController
  before_action :set_diet, only: [:show, :edit, :update, :destroy]

  # GET /diets
  # GET /diets.json
  def index
    @diets = Diet.all
  end

  # GET /diets/1
  # GET /diets/1.json
  def show
  end

  # GET /diets/new
  def new
    @diet = Diet.new
  end

  # GET /diets/1/edit
  def edit
  end

  # POST /diets
  # POST /diets.json
  def create
    @diet = Diet.new(diet_params)

    respond_to do |format|
      if @diet.save
        format.html { redirect_to @diet, notice: 'Diet was successfully created.' }
        format.json { render :show, status: :created, location: @diet }
      else
        format.html { render :new }
        format.json { render json: @diet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diets/1
  # PATCH/PUT /diets/1.json
  def update
    respond_to do |format|
      if @diet.update(diet_params)
        format.html { redirect_to @diet, notice: 'Diet was successfully updated.' }
        format.json { render :show, status: :ok, location: @diet }
      else
        format.html { render :edit }
        format.json { render json: @diet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diets/1
  # DELETE /diets/1.json
  def destroy
    @diet.destroy
    respond_to do |format|
      format.html { redirect_to diets_url, notice: 'Diet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diet
      @diet = Diet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diet_params
      params.require(:diet).permit(:name, :description, :icon, :image, :published, :heroclass)
    end
end

app/helpers/diets_helper.rb
module DietsHelper
end

app/views/diets/_form.html.erb
<%= form_for @diet, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :icon, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :icon, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :image, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :published, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :published, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :heroclass, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :heroclass, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  diets_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/diets/edit.html.erb
<%- model_class = Diet -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Diet %></h1>
</div>
<%= render :partial => 'form' %>

app/views/diets/index.html.erb
<%- model_class = Diet -%>
<div class="page-header">
  <h1><%=t '.title', :default => Diet %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:icon) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:published) %></th>
      <th><%= model_class.human_attribute_name(:heroclass) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @diets.each do |diet| %>
      <tr>
        <td><%= diet.id %></td>
        <td><%= diet.name %></td>
        <td><%= diet.description %></td>
        <td><%= diet.icon %></td>
        <td><%= diet.image %></td>
        <td><%= diet.published %></td>
        <td><%= diet.heroclass %></td>
        <td><%=l diet.created_at, format: :long %></td>
        <td>
          <%= link_to diet_path(diet), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to diet_path(diet), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_diet_path,
            :class => 'btn btn-primary' %>

app/views/diets/new.html.erb
<%- model_class = Diet -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Diet %></h1>
</div>
<%= render :partial => 'form' %>

app/views/diets/show.html.erb
<%- model_class = Diet -%>
<div class="page-header">
  <h1><%=t '.title', :default => Diet %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @diet.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @diet.description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:icon) %></dt>
      <dd><pre class="prettyprint"><%= @diet.icon %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:image) %></dt>
      <dd><pre class="prettyprint"><%= @diet.image %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:published) %></dt>
      <dd><pre class="prettyprint"><%= @diet.published %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:heroclass) %></dt>
      <dd><pre class="prettyprint"><%= @diet.heroclass %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              diets_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_diet_path(@diet), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              diet_path(@diet),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>