config/routes.rb
Rails.application.routes.draw do
  resources :recipes do
  member do
    get "vote"
  end
end

  resources :categories

  resources :occasions

  resources :diets

  resources :cusines

  resources :eases

  resources :preferences

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'recipes#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/occasion.rb
class Occasion < ActiveRecord::Base
  has_and_belongs_to_many :recipes
end

app/controllers/occasions_controller.rb
class OccasionsController < ApplicationController
  before_action :set_occasion, only: [:show, :edit, :update, :destroy]

  # GET /occasions
  # GET /occasions.json
  def index
    @occasions = Occasion.all
  end

  # GET /occasions/1
  # GET /occasions/1.json
  def show
  end

  # GET /occasions/new
  def new
    @occasion = Occasion.new
  end

  # GET /occasions/1/edit
  def edit
  end

  # POST /occasions
  # POST /occasions.json
  def create
    @occasion = Occasion.new(occasion_params)

    respond_to do |format|
      if @occasion.save
        format.html { redirect_to @occasion, notice: 'Occasion was successfully created.' }
        format.json { render :show, status: :created, location: @occasion }
      else
        format.html { render :new }
        format.json { render json: @occasion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /occasions/1
  # PATCH/PUT /occasions/1.json
  def update
    respond_to do |format|
      if @occasion.update(occasion_params)
        format.html { redirect_to @occasion, notice: 'Occasion was successfully updated.' }
        format.json { render :show, status: :ok, location: @occasion }
      else
        format.html { render :edit }
        format.json { render json: @occasion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /occasions/1
  # DELETE /occasions/1.json
  def destroy
    @occasion.destroy
    respond_to do |format|
      format.html { redirect_to occasions_url, notice: 'Occasion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_occasion
      @occasion = Occasion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def occasion_params
      params.require(:occasion).permit(:name, :description, :icon, :image, :published, :heroclass)
    end
end

app/helpers/occasions_helper.rb
module OccasionsHelper
end

app/views/occasions/_form.html.erb
<%= form_for @occasion, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :icon, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :icon, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :image, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :published, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :published, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :heroclass, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :heroclass, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  occasions_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/occasions/edit.html.erb
<%- model_class = Occasion -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Occasion %></h1>
</div>
<%= render :partial => 'form' %>

app/views/occasions/index.html.erb
<%- model_class = Occasion -%>
<div class="page-header">
  <h1><%=t '.title', :default => Occasion %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:icon) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:published) %></th>
      <th><%= model_class.human_attribute_name(:heroclass) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @occasions.each do |occasion| %>
      <tr>
        <td><%= occasion.id %></td>
        <td><%= occasion.name %></td>
        <td><%= occasion.description %></td>
        <td><%= occasion.icon %></td>
        <td><%= occasion.image %></td>
        <td><%= occasion.published %></td>
        <td><%= occasion.heroclass %></td>
        <td><%=l occasion.created_at, format: :long %></td>
        <td>
          <%= link_to occasion_path(occasion), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to occasion_path(occasion), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_occasion_path,
            :class => 'btn btn-primary' %>

app/views/occasions/new.html.erb
<%- model_class = Occasion -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Occasion %></h1>
</div>
<%= render :partial => 'form' %>

app/views/occasions/show.html.erb
<%- model_class = Occasion -%>
<div class="page-header">
  <h1><%=t '.title', :default => Occasion %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @occasion.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @occasion.description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:icon) %></dt>
      <dd><pre class="prettyprint"><%= @occasion.icon %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:image) %></dt>
      <dd><pre class="prettyprint"><%= @occasion.image %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:published) %></dt>
      <dd><pre class="prettyprint"><%= @occasion.published %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:heroclass) %></dt>
      <dd><pre class="prettyprint"><%= @occasion.heroclass %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              occasions_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_occasion_path(@occasion), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              occasion_path(@occasion),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>